package master;

import shared.TaskMessage;
import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.util.concurrent.atomic.AtomicInteger;

public class SplitMergeExecutor {

    private List<SlaveHandler> slaves;
    private static final AtomicInteger globalSlaveCounter = new AtomicInteger(0);

    public SplitMergeExecutor(List<SlaveHandler> slaves) {
        this.slaves = slaves;
    }

    public byte[] execute(TaskMessage msg) throws Exception {
        if (slaves.isEmpty()) {
            throw new RuntimeException("No slaves connected.");
        }

        // 1. Setup working directory
        File workDir = new File("masterTask_" + System.currentTimeMillis());
        workDir.mkdirs();

        File masterJar = new File(workDir, msg.getMasterJarName());
        File inputFile = new File(workDir, msg.getFileName());

        Files.write(masterJar.toPath(), msg.getMasterJarContent());
        Files.write(inputFile.toPath(), msg.getFileContent());

        // 2. PHASE SPLIT: Exécution du Master task jar
        System.out.println("Master: Splitting task...");
        ProcessBuilder pb = new ProcessBuilder(
                "java", "-jar", masterJar.getName(), msg.getMasterOptions(), inputFile.getName());
        pb.directory(workDir);
        pb.start().waitFor();

        // 3. Collect sub-files (les fichiers qui commencent par "sub")
        File[] subFiles = workDir.listFiles((dir, name) -> name.toLowerCase().startsWith("sub"));
        if (subFiles == null || subFiles.length == 0)
            throw new RuntimeException("No sub files generated by master jar.");

        Arrays.sort(subFiles);
        int parts = subFiles.length;

        // 4. PHASE PROCESS: Distribution aux Slaves
        ExecutorService executor = Executors.newFixedThreadPool(Math.min(slaves.size(), parts));
        List<Future<String>> resultsFutures = new ArrayList<>();

        // Détecter l'extension pour savoir comment enregistrer les résultats
        String inputExtension = msg.getFileName().contains(".")
                ? msg.getFileName().substring(msg.getFileName().lastIndexOf("."))
                : ".tmp";

        for (int i = 0; i < parts; i++) {
            final int index = i;
            final File subFile = subFiles[i];
            // final SlaveHandler slave = slaves.get(i % slaves.size());
            int nextSlaveIndex = Math.abs(globalSlaveCounter.getAndIncrement() % slaves.size());
            final SlaveHandler slave = slaves.get(nextSlaveIndex);

            Callable<String> task = () -> {
                TaskMessage slaveMsg = new TaskMessage(
                        null, null, null,
                        msg.getSlaveJarName(), msg.getSlaveJarContent(), msg.getSlaveOptions(),
                        subFile.getName(), Files.readAllBytes(subFile.toPath()));

                slave.sendTask(slaveMsg);
                TaskMessage response = slave.getResult();

                // Sauvegarder le sous-résultat avec la bonne extension
                String resultName = "result" + index + inputExtension;
                File resultFile = new File(workDir, resultName);
                Files.write(resultFile.toPath(), response.getResultFile());

                return resultName;
            };
            resultsFutures.add(executor.submit(task));
        }

        // Attendre la fin de tous les Slaves
        for (Future<String> f : resultsFutures) {
            f.get();
        }
        executor.shutdown();

        // 5. PHASE MERGE: Choix de la méthode de fusion selon le type de fichier
        System.out.println("Master: Merging results...");
        if (isImage(inputExtension)) {
            return mergeImages(workDir, parts, inputExtension.replace(".", ""));
        } else {
            return mergeTextFiles(workDir, parts, inputExtension);
        }
    }

    // --- Helper: Fusion des images ---
    private byte[] mergeImages(File workDir, int parts, String format) throws Exception {
        BufferedImage[] images = new BufferedImage[parts];
        int totalHeight = 0, width = 0;

        for (int i = 0; i < parts; i++) {
            File f = new File(workDir, "result" + i + "." + format);
            images[i] = ImageIO.read(f);
            totalHeight += images[i].getHeight();
            width = Math.max(width, images[i].getWidth());
        }

        BufferedImage finalImage = new BufferedImage(width, totalHeight, BufferedImage.TYPE_INT_RGB);
        int currentY = 0;
        for (BufferedImage img : images) {
            finalImage.getGraphics().drawImage(img, 0, currentY, null);
            currentY += img.getHeight();
        }

        File finalFile = new File(workDir, "FinalResult." + format);
        ImageIO.write(finalImage, format, finalFile);
        return Files.readAllBytes(finalFile.toPath());
    }

    // --- Helper: Fusion des fichiers texte (Matrices) ---
    private byte[] mergeTextFiles(File workDir, int parts, String ext) throws Exception {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < parts; i++) {
            File f = new File(workDir, "result" + i + ext);
            List<String> lines = Files.readAllLines(f.toPath());
            for (String line : lines) {
                sb.append(line).append(System.lineSeparator());
            }
        }
        File finalFile = new File(workDir, "FinalResult" + ext);
        Files.write(finalFile.toPath(), sb.toString().getBytes());
        return Files.readAllBytes(finalFile.toPath());
    }

    private boolean isImage(String ext) {
        ext = ext.toLowerCase();
        return ext.endsWith(".jpg") || ext.endsWith(".jpeg") || ext.endsWith(".png") || ext.endsWith(".bmp");
    }
}